apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: usdv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: usdv
    app.kubernetes.io/part-of: byoc-app-oojb
  name: usdv
spec:
  rules:
  - host: usdv-byoc-cojv-tenant.apps.1549092aa66a63e8e26e.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: usdv
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
