apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: usdv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: usdv
    app.kubernetes.io/part-of: byoc-app-oojb
  name: usdv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: usdv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: usdv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-cojv-tenant/byoc-app-oojb/usdv@sha256:1cc84afc4b71f6a2c175b5af35304638ff77428fe8afce5fd929531735e7a056
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
